[theme]
base = "dark"
primaryColor = "#7CFC00"
backgroundColor = "#0a0a0a"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#ffffff"
linkColor = "#9FFF4D"
borderColor = "#253A10"
baseRadius = "12px"

[theme.sidebar]
backgroundColor = "#000000"
secondaryBackgroundColor = "#141414"

[browser]
gatherUsageStats = false
