"""Generate the app theme from the house style.

The website used a palette that matched nothing else in the project: the
report figures, the logo and the favicon are all drawn in the house accent
(:class:`groundwater.config.HouseStyle`), so a visitor met a blue droplet on a
green page. The colours the client sees in a .docx and the colours they see on
the website should be the same colours.

Writes ``.streamlit/config.toml``. ``web/build_demo.py`` reads that file, so the
browser demo follows automatically and there is exactly one palette:

    python web/make_theme.py

Every derived colour is checked against WCAG AA contrast before it is written,
so a change to the house accent cannot quietly produce unreadable text.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

from groundwater.config import HouseStyle  # noqa: E402

# The wordmark ink from web/make_brand_assets.py: darker than the accent, and
# already the colour of the logo's lettering.
INK = "#173B54"


def _rgb(colour: str) -> tuple[float, float, float]:
    colour = colour.lstrip("#")
    return tuple(int(colour[i : i + 2], 16) / 255 for i in (0, 2, 4))


def _luminance(colour: str) -> float:
    def channel(c: float) -> float:
        return c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4

    r, g, b = (channel(c) for c in _rgb(colour))
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def contrast(a: str, b: str) -> float:
    """WCAG contrast ratio between two hex colours."""
    la, lb = sorted((_luminance(a), _luminance(b)))
    return (lb + 0.05) / (la + 0.05)


def _mix(colour: str, other: str, amount: float) -> str:
    """Blend two hex colours; ``amount`` is how much of ``other`` to take."""
    mixed = (
        round(255 * (c1 + (c2 - c1) * amount))
        for c1, c2 in zip(_rgb(colour), _rgb(other))
    )
    return "#" + "".join(f"{value:02X}" for value in mixed)


def palette(style: HouseStyle | None = None) -> dict[str, str]:
    """The UI palette, derived from the house accent."""
    style = style or HouseStyle()
    accent = style.accent_color
    white = "#FFFFFF"
    return {
        "base": "light",
        # The accent carries buttons, focus rings and the active nav item.
        "primaryColor": accent,
        "backgroundColor": white,
        # Surfaces are the accent at low strength, so panels read as part of
        # the same family rather than as grey boxes.
        "secondaryBackgroundColor": _mix(white, accent, 0.06),
        "textColor": INK,
        "linkColor": accent,
        "borderColor": _mix(white, accent, 0.22),
        "baseRadius": "0.6rem",
        "sidebarBackgroundColor": _mix(white, accent, 0.10),
        "sidebarSecondaryBackgroundColor": white,
    }


def check(colours: dict[str, str]) -> list[str]:
    """WCAG AA checks on the pairs a reader actually has to read."""
    problems = []
    pairs = [
        ("body text on the page", colours["textColor"], colours["backgroundColor"], 4.5),
        ("body text on panels", colours["textColor"], colours["secondaryBackgroundColor"], 4.5),
        ("body text in the sidebar", colours["textColor"], colours["sidebarBackgroundColor"], 4.5),
        ("links on the page", colours["linkColor"], colours["backgroundColor"], 4.5),
        ("button label on the accent", "#FFFFFF", colours["primaryColor"], 4.5),
    ]
    for label, fg, bg, minimum in pairs:
        ratio = contrast(fg, bg)
        if ratio < minimum:
            problems.append(f"{label}: {fg} on {bg} is {ratio:.2f}:1, needs {minimum}")
    return problems


TEMPLATE = """# Generated by web/make_theme.py from groundwater.config.HouseStyle.
# Edit the house style (or this generator) and re-run, rather than editing here:
# web/build_demo.py reads this file, so the browser demo follows automatically.
[theme]
base = "{base}"
primaryColor = "{primaryColor}"
backgroundColor = "{backgroundColor}"
secondaryBackgroundColor = "{secondaryBackgroundColor}"
textColor = "{textColor}"
linkColor = "{linkColor}"
borderColor = "{borderColor}"
baseRadius = "{baseRadius}"

[theme.sidebar]
backgroundColor = "{sidebarBackgroundColor}"
secondaryBackgroundColor = "{sidebarSecondaryBackgroundColor}"

[browser]
gatherUsageStats = false
"""


def render(colours: dict[str, str] | None = None) -> str:
    return TEMPLATE.format(**(colours or palette()))


def main() -> None:
    colours = palette()
    problems = check(colours)
    for problem in problems:
        print(f"contrast: {problem}")
    if problems:
        raise SystemExit("theme not written: fix the contrast failures above")

    out = REPO / ".streamlit" / "config.toml"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(colours), encoding="utf-8")
    print(f"wrote {out}")
    for name, value in colours.items():
        print(f"  {name:32s} {value}")


if __name__ == "__main__":
    main()
